#!/bin/bash
# snotes-1.0 by v4hn / 2009-2013
# See LICENSE file for copyright and license details.

info(){
    echo "$0: Info: $1" >&2
}

die(){
    echo "$0: Error: $1" >&2
    exit 1
}

while [ -n "$1" ]; do
    case "$1" in
    "-s"|"--search")
        SNOTES_SEARCH="yes"
        shift;;
    *)
        echo "usage: $0 [-s|--search]"
        die "unknown parameter '$1'"
        ;;
    esac
done

. "$HOME/.snotes/config" ||
    die "config ~/.snotes/config messed up"

type dmenu >/dev/null 2>&1 ||
    die "dmenu not available"

type git >/dev/null 2>&1 ||
    die "git not in PATH"

SNOTES_DONTLIST_REGEXP="${SNOTES_DONTLIST_REGEXP:-^$}"

IFS=:
if [ "${SNOTES_SEARCH}" = "yes" ]; then
    regex="$(echo | dmenu -p 'Search for:')"
    [ -n "$regex" ] || exit 0 # no regex means we don't need to search
    note="$( snotes-search ${regex} | snotes-ignore | sort -u | m)"
else
    note="$(snotes-list | snotes-ignore | sort | m)"
fi

if [ -z "$note" ]; then
    exit 0
fi
unset IFS

vise "${note}"

snotes-cleanup "${note}"
