#!/bin/sh
# snotes-1.0 by v4hn / 2009-2013
# See LICENSE file for copyright and license details.

info(){
    echo "$0: Info: $1" >&2
}

die(){
    echo "$0: Error: $1" >&2
    exit 1
}

while [ -n "$1" ]; do
    case "$1" in
    "-s"|"--search")
        SNOTES_SEARCH="yes"
        shift;;
    *)
        echo "usage: $0 [-s|--search]"
        die "unknown parameter '$1'"
        ;;
    esac
done

if [ ! -f "$HOME/.snotes/config" ]; then
    info "creating config file ~/.snotes/cofig"
    cat > "$HOME/.snotes/config" <<'EOF'
SNOTES_EDITOR="xterm -e ${VISUAL:-${EDITOR:-vi}}"
SNOTES_DB="$HOME/.snotes/notes"

#DMENU_ARGS="-p Open: -sb darkgreen"

# clean trailing whitespace from file automatically
SNOTES_CLEANUP="yes"

# files you don't want to be cleaned
#SNOTES_DONTCLEAN_REGEXP='^.*\.gpg$|^.*\.asc$'
SNOTES_DONTCLEAN_REGEXP='^$'

# files you don't want to see in listings and search
SNOTES_DONTLIST_REGEXP='^(\.gitignore|.*\.swp)$'

# which char should be used to prefix additional options ('changed', etc.)
SNOTES_OPTION_CHAR='!'

# how many commits should be shown for "changed:note"
SNOTES_CHANGED_COMMITS=2
EOF
fi

. "$HOME/.snotes/config" ||
    die "config ~/.snotes/config messed up"

type dmenu >/dev/null 2>&1 ||
    die "dmenu not available"

type git >/dev/null 2>&1 ||
    die "git not in PATH"

SNOTES_DONTLIST_REGEXP="${SNOTES_DONTLIST_REGEXP:-^$}"

IFS=:
if [ "${SNOTES_SEARCH}" = "yes" ]; then
    regex="$(echo | m)"
    [ -n "$regex" ] || exit 0 # no regex means we don't need to search
    select="$( snotes-search ${regex} | snotes-ignore | sort -u | m)"
else
    select="$(snotes-list | snotes-ignore | sort | m)"
fi

if [ -z "$select" ]; then
    exit 0
fi
unset IFS

case "${select##*${SNOTES_OPTION_CHAR}}" in
blame|b)
    file="blame:${select%${SNOTES_OPTION_CHAR}*}"
    ;;
changed|c)
    file="changed:${select%${SNOTES_OPTION_CHAR}*}"
    ;;
*)
    file="note:${select}"
esac

exec snotes-open "$file"
