#!/usr/bin/bash
set -x

function is_empty()
{
	stest -vs "${1}"
}

function is_valid()
{
	echo "${1}" | snotes-ignore
}

function delete_note()
{
	local note="${1}"
	git rm "${note}"
	git commit -m "deleted '${note}'" -- "${@}"
}

function main()
{
	local note="${1}"
	local dict="${2}"

	if is_empty "${note}" && is_valid "${note}"; then
		delete_note "${note}" "${dict}"
	fi
}

main ${@}
