#!/usr/bin/bash
set -x

function is_empty()
{
	stest -vs "${1}"
}

function is_protected()
{
	echo "${1}" | snotes-ignore
}

function delete_note()
{
	local note="${1}"
	git rm "${note}"
	git commit -m "deleted '${note}'" -- "${note}"
}

function main()
{
	local note="${1}"

	if is_empty "${note}" && !is_protected "${note}"; then
		delete_note "${note}"
	fi
}

main ${@}
